apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ index .Values "backend-component" "deployment" "name" }}
  labels:
    {{- include "sync-along.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sync-along.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sync-along.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sync-along.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ index .Values "backend-component" "deployment" "image" "repository" }}:{{ index .Values "backend-component" "deployment" "image" "tag" | default .Chart.AppVersion }}"
          imagePullPolicy: {{ index .Values "backend-component" "deployment" "image" "pullPolicy" }}
          ports:
            - name: http
              containerPort: 4001
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: REDIS_HOST
            value: "redis-13406.c1.asia-northeast1-1.gce.cloud.redislabs.com"
          - name: REDIS_PORT
            value: "13406"
          - name: REDIS_PASSWORD
            value: "HOBL9WbJWOuNUaFBnTFPBxS49sVFQSyu"
          - name: MONGODB_CONNECTION_URL
            value: "mongodb+srv://admin:admin@cluster0.csain.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
